theme_color: "#16A085"


top_nav_mobile_enter_animation: animate__zoomInUp
top_nav_mobile_exit_animation: animate__zoomOutDown


language: fa_IR
direction: rtl

title: آکام محبی
description: وبلاگ شخصی آکام، دست نوشته های یک گیک
title_sep: '-'

top_nav: top_menu
bottom_nav: footer



permalink: /:year/:month/:slug/

excerpt_separator: '<div id="read-more"></div>'

collections:
    assets:
        output: true
        permalink: /:path
    pages:
        output: true
        permalink: /:slug/
    projects:
        output: true
        permalink: /projects/:slug/
    trading_journal:
        output: true
        permalink: /trading-journal/:year/:month/:day/

defaults:
    -
        scope:
            path: ""
        values:
            seo_description_max_words: 200
            lang: "fa_IR"
    -
        scope:
            path: ""
            type: "projects"
        values:
            layout: single
            type: project
            support: true
    -
        scope:
            path: ""
            type: "pages"
        values:
            layout: single
            type: page
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: single
            type: post
            comments: true
    -
        scope:
            path: ""
            type: "trading_journal"
        values:
            layout: single
            type: item

plugins:
    - jekyll-seo-tag





exclude:
    - LICENSE
    - README.md